url: https://jackcarey.github.io
baseurl: /astral-jekyll

sass:
  sass_dir: ./assets/sass/
  style: compressed
css:

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  index_collection:
    output: true
    permalink: /#:title

defaults:
  -
    scope:
      path: "/"
    values:
      layout: "articles"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope: # fallback on the default layout
      path: ""
    values:
      layout: "default"